### ISSUE TITLE
Pass the FxA uid and x-client-state through to storage nodes

### ISSUE THREAD

**Issue by rfk** [mozilla-services/tokenserver#121]
Our new durable storage nodes [1] will be backed by automagically-scalable databases such as Google Spanner, which implement their own internal sharding logic.  For such databases, the way that tokenserver allocates sequential integer userids will be a liability, since sequential primary keys cause hotspots that defeat the internal sharding logic [2].

The FxA uid would be a suitable primary key, since it's a randomly-generated string rather than a sequential integer.  But the storage nodes can't just use the FxA uid as their primary key, because they need to enforce separation of data that belongs to the same user but is encrypted with different keys.

I think the best primary key for such databases will be a compound primary key consisting of the FxA uid and the "x-client-state" token, which is a unique identifier for the current encryption key.  This will allow them to segregate data that has been encrypted with different keys, while still being able to enumerate all records associated with a particular user (which is important for GDPR compliance and for general cleanup purposes).

To allow this to work, tokenserver will need to include the user's FxA uid and x-client-state token in the Hawk token id payload constructed here:

  https://github.com/mozilla-services/tokenserver/blob/master/tokenserver/views.py#L403

As well as in the synthetic tokens that it uses for doing background cleanup here:

  https://github.com/mozilla-services/tokenserver/blob/master/tokenserver/scripts/purge_old_records.py#L91

The storage node can then extract them from the Hawk token and use them as primary key for its database queries.

Some related thoughts:

* This scheme will prevent us from doing a "synthetic" node migration that wipes a user's sync data without resetting their password.  That's probably for the best, as the whole point of building durable storage nodes is that we'll stop doing non-password-reset-related node migrations.

* The Hawk token id already contains a field called "fxa_uid", but this field is the hashed "metrics id" generated at [3].  We shouldn't use that for db primary key because it's not a guaranteed stable identifier (it's produced via hmac with a server-side secret).  We could use a different field name, or we could figure out how to migrate the existing field to a new name like "hashed_fxa_uid".

* When tokenserver was originally designed, we intentionally did not pass through the underlying user identity, and the sequential numeric uids provided a kind of anonymization of the data on the storage nodes.  I don't think anonymization is providing us much value in practice these days, and no other FxA-connected service does it, so I'm not worried about dropping it.  But perhaps we should get a quick sanity-check from legal etc?

* An advantage of this scheme is that the durable storage nodes could, in future, learn to accept FxA OAuth tokens directly for authentication rather than indirecting via the tokenserver.  This puts us on a path to deprecating tokenserver entirely one day, which I like.

/cc @bbangert; thoughts?

[1] https://github.com/mozilla-services/syncstorage-rs/
[2] https://cloud.google.com/spanner/docs/schema-and-data-model#primary_keys
[3] https://github.com/mozilla-services/tokenserver/blob/master/tokenserver/views.py#L158

**Comment by bbangert** [comment]
I think this is a great way to go forward with NoSQL user storage systems. I've included a change in the new sync server code to accommodate the eventual filing of this other user id.

**Comment by pjenvey** [comment]
@rfk did #122 fully close this out?

**Comment by rfk** [comment]
Yes, we can replace this with https://github.com/mozilla-services/tokenserver/issues/124 for some follow-up work that's blocked on FxA
