### ISSUE TITLE
Set protected status on production branch

### ISSUE THREAD

**Issue by moz-hwine** [mozilla-services/tokenserver#133]
Hello! This is your neighborhood secops team looking out for you!

The production branch on this repository is not protected against force pushes. This setting is recommended as part of [Mozilla's Guidelines][guidelines_url] for a Sensitive Repository.

**Anyone with admin permissions for this repository can correct the setting using [this URL][protect_url].**

If you have any questions, or believe this issue was opened in error, please contact [us][email] and mention SOGH001-0 and this repository.

Thank you for your prompt attention to this issue.
--Firefox Operations Security team

[guidelines_url]: https://wiki.mozilla.org/GitHub/Repository_Security
[protect_url]: https://github.com/mozilla-services/tokenserver/settings/branches
[email]: <mailto:secops+gh001@mozilla.com?subject=SOGH001-0+Question+re+mozilla-services/tokenserver>

**Comment by rfk** [comment]
Thank you! I've set up `master` with branch protection, and also to require reviews and signed commits.
