### ISSUE TITLE
Adjust routing logic for new users to allow us to point X% of them to Spanner.

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/tokenserver#159]
We're planning to rollout Durable Sync for brand new users of Sync only to start with. Before we can move to [phase 2](https://docs.google.com/document/d/1ULkyVWBeIt0zYo4AmF5aUI1kRDKCPQQaXVZv1w1oj_M/edit#), we'll need to adjust the logic here to make it easy to route users by a percentage.

Ideally, that percentage can be pulled from a config value somewhere so we can easily modify it without a deploy.

Once a user has been routed to Spanner, we'll need to continue routing them over to Spanner for subsequent sessions.

It looks like the logic for routing a new user lives [here](https://github.com/mozilla-services/tokenserver/blob/eeb982fafcdac187061c7b7b62d92a28e75f0d63/tokenserver/views.py#L371) for reference.

**Comment by tublitzed** [comment]
This is going to Donovan once we get him access to this repo.

**Comment by fzzzy** [comment]
@rfk can you give me permissions for this repo and assign this to me?

**Comment by rfk** [comment]
Somehow I can't, I think I've lost my admin rights to this repo :-(

I'll see if I can track down someone who does.

**Comment by rfk** [comment]
We may need to ask @tblow for help with admin settings here; ideally we wind up with:

* @fzzzy and @jrconlin added to the sync-devs team
* At least one member of the sync-devs team promoted to maintainer status for said team, so we can manage that ourselves in future

**Comment by rfk** [comment]
The above has made its way into the correct place for actioning such requests (which for future reference, is as an issue in https://github.com/mozilla-services/github-management/) and I'll update here once it's complete.

**Comment by rfk** [comment]
@fzzzy you should now have access to the repo; let me know if something isn't working as expect.

**Comment by fzzzy** [comment]
Seems to be working, thanks!
