### ISSUE TITLE
KeyError: 'keys_changed_at'

### ISSUE THREAD

**Issue by 0x0ptr** [mozilla-services/tokenserver#161]
Hi!

I am running tokenserver 1.5.0 on my Arch Linux server to locally sync my Firefox. It has been working but some time ago (don't know when) I must have upgraded tokenserver and now it is not working anymore. I noticed that in the log I see the following:
`
File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
    result = view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
    response = view(request)
  File "/usr/lib/python2.7/site-packages/cornice/service.py", line 514, in wrapper
    response = view_(request)
  File "/usr/lib/python2.7/site-packages/tokenserver/views.py", line 384, in return_token
    if keys_changed_at > user['keys_changed_at']:
KeyError: 'keys_changed_at'
[pid: 13356|app: 0|req: 1/1] 192.168.4.100 () {50 vars in 2951 bytes} [Sun Dec 15 21:03:06 2019] GET /ffsync/token/1.0/sync/1.5 => generated 0 bytes in 5530 msecs (HTTP/2.0 500) 0 headers in 0 bytes (0 switches on core 0)
`
I looked at my sqlite3 database file and I see that "keys_changed_at" is not part of the schema for users in the database. So I tried to delete the database and restart uwsgi to recreate the DB and then sync back my data. The database got recreated but the schema didn't change!?!

Any ideas what I am missing and what is wrong and how to fix this?

Thanks!

**Comment by rfk** [comment]
The `keys_changed_at` stuff is pretty new, are you running tokenserver from the latest `master` from github?

>  The database got recreated but the schema didn't change!?!

I'm not sure what could cause this, since `keys_changed_at` is definitely in the latest schema. I can try to repro locally once I know what version/commit you're running on.

**Comment by pjenvey** [comment]
The keys_changed_at column was added a couple months ago. tokenserver's schema changes are managed by the Alembic migration tool.

It appears these migrations are not run automatically, I've logged #162 for the need to be clearer about this.

Until it's formally documented I can point you to: https://alembic.sqlalchemy.org/en/latest/tutorial.html#running-our-first-migration and note there's an associated alembic.ini file in the root directory of this repo for running the migration tool.

**Comment by 0x0ptr** [comment]
> The `keys_changed_at` stuff is pretty new, are you running tokenserver from the latest `master` from github?

I am running https://github.com/mozilla-services/tokenserver/archive/1.5.0.tar.gz
Installed on Arch Linux from https://aur.archlinux.org/packages/python2-tokenserver/
