### ISSUE TITLE
Provide a "dynamic_settings" table in SQL for ops

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/tokenserver#165]
Ops has noted that updating a setting in a SQL table does not require a redepoyment. For certain settings, it may be more useful to have a "settings" table that they can modify on the fly.

**Comment by rfk** [comment]
As noted in https://github.com/mozilla-services/tokenserver/pull/166#pullrequestreview-341465648, I have a mild security-related objection to putting application config inside the application's working data space. I don't think it'll be a problem in this particular case, but I'd be uncomfortable generalizing this approach very far.
