### ISSUE TITLE
Cannot start 1.5.6 docker container (ContextualVersionConflict cffi)

### ISSUE THREAD

**Issue by jrgm** [mozilla-services/tokenserver#187]
Seeing the below exception on stage, but can also be done locally with `docker run mozilla/tokenserver:1.5.6 server`

```
Jun 12 02:52:30 ip-172-31-63-217.ec2.internal docker-tokenserver[11606]: {"v": 1, "hostname": "ip-172-31-63-217.ec2.internal", \
  "op": "gunicorn.error", "name": "gunicorn.error", "time": "2020-06-12T02:52:30.398046Z", "pid": 12, \
  "message": "Exception in worker process", \
  "error": "ContextualVersionConflict(cffi 1.13.2 (/usr/local/lib_pypy), Requirement.parse('cffi==1.12.2'), set(['tokenserver']))", \
  "traceback": "Uncaught exception:
  File \"/usr/local/site-packages/gunicorn/arbiter.py\", line 586, in spawn_worker
    worker.init_process()
  File \"/usr/local/site-packages/gunicorn/workers/base.py\", line 135, in init_process
    self.load_wsgi()
  File \"/usr/local/site-packages/gunicorn/workers/base.py\", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File \"/usr/local/site-packages/gunicorn/app/base.py\", line 67, in wsgi
    self.callable = self.load()
  File \"/usr/local/site-packages/gunicorn/app/wsgiapp.py\", line 50, in load
    return self.load_pasteapp()
  File \"/usr/local/site-packages/gunicorn/app/wsgiapp.py\", line 46, in load_pasteapp
    return load_pasteapp(self.cfgurl, self.relpath, global_conf=self.cfg.paste_global_conf)
  File \"/usr/local/site-packages/gunicorn/app/pasterapp.py\", line 71, in load_pasteapp
    global_conf=global_conf)
  File \"/usr/local/site-packages/paste/deploy/loadwsgi.py\", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File \"/usr/local/site-packages/paste/deploy/loadwsgi.py\", line 277, in loadobj
    global_conf=global_conf)
  File \"/usr/local/site-packages/paste/deploy/loadwsgi.py\", line 302, in loadcontext
    global_conf=global_conf)
  File \"/usr/local/site-packages/paste/deploy/loadwsgi.py\", line 326, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File \"/usr/local/site-packages/paste/deploy/loadwsgi.py\", line 455, in get_context
    global_additions=global_additions)
  File \"/usr/local/site-packages/paste/deploy/loadwsgi.py\", line 564, in _pipeline_app_context
    APP, pipeline[-1], global_conf)
  File \"/usr/local/site-packages/paste/deploy/loadwsgi.py\", line 459, in get_context
    section)
  File \"/usr/local/site-packages/paste/deploy/loadwsgi.py\", line 481, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File \"/usr/local/site-packages/paste/deploy/loadwsgi.py\", line 412, in get_context
    global_conf=global_conf)
  File \"/usr/local/site-packages/paste/deploy/loadwsgi.py\", line 302, in loadcontext
    global_conf=global_conf)
  File \"/usr/local/site-packages/paste/deploy/loadwsgi.py\", line 334, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File \"/usr/local/site-packages/paste/deploy/loadwsgi.py\", line 625, in get_context
    object_type, name=name)
  File \"/usr/local/site-packages/paste/deploy/loadwsgi.py\", line 645, in find_egg_entry_point
    pkg_resources.require(self.spec)
  File \"/usr/local/site-packages/pkg_resources/__init__.py\", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File \"/usr/local/site-packages/pkg_resources/__init__.py\", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
<class 'pkg_resources.ContextualVersionConflict'>
ContextualVersionConflict(cffi 1.13.2 (/usr/local/lib_pypy), Requirement.parse('cffi==1.12.2'), set(['tokenserver']))
"}
```

**Comment by fzzzy** [comment]
@jrconlin Have you seen anything like this before when you were trying to get the tokenserver running with changes before?

**Comment by jrconlin** [comment]
@fzzzy Not with cffi specifically, but I've seen stuff like this. The problem is that there are some other crates that may be bringing in a conflicting version of `cffi`. I solved mine by locking the version in my Cargo.toml, but you may need to use `cargo tree` to identify which crate is making the explicit request and either back versioning that crate or bumping up the local version of `cffi`.

**Comment by fzzzy** [comment]
This is in the python version...

**Comment by jrconlin** [comment]
Ah, sorry, missed that. Let me see if I can replicate locally and see what's up. Honestly, what I said above might even be more so, since a lot of python packages are growing less and less able to run  under python2.7. So we have to nail down all sorts of sub-dependencies.

**Comment by jrconlin** [comment]
So, a few things I'm seeing at least locally.
1) I'm not hitting the `cffi` issue doing local builds, but pulling the docker image definitely hits it. I'm going to guess that it's probably either a build problem on the remote machines or an unfixed dependency issue. I added 
`gunicorn == 19.10.0` to my `requirements.txt` file because the local build docker image didn't find it. That got me a bit further, but then...

2) Looks like alpine might have switched from `libmysqlclient-dev` to `mariadb-dev`, and it's causing some problems with interpolation. Looking at what's going on in there.

Yay! this stuff is a mess and only getting worse.

**Comment by fzzzy** [comment]
Can we pin alpine to an old version to avoid this? (What's alpine? :)

**Comment by jrconlin** [comment]
[Alpine](https://hub.docker.com/_/alpine) is the root OS for the pypy:2.7-jesse container. (At least as I understand. When I built the docker locally, that's the core that was brought in, and what I got dumped into when I did a `docker run -it --entrypoint sh tokenserver`. 

It's very minimal, so I'm sure that some other docker is probably building out the db dependencies, but the effect is the same.  There's definitely bit rot going on in here.

**Comment by jrgm** [comment]
See https://github.com/mozilla-services/tokenserver/pull/189

**Comment by tublitzed** [comment]
@jrgm - can you confirm this was resolved [here](https://github.com/mozilla-services/tokenserver/pull/189), or should we keep this one open?

**Comment by pjenvey** [comment]
pypy ships w/ its own cffi, so any version differing from what it provides will trigger a conflict. A more future proof way to avoid this is to only require cffi on python, e.g. in requirements.txt:

`
cffi==1.13.2 ; platform_python_implementation == "CPython"
`

**Comment by jrgm** [comment]
@tublitzed - yes. I'll close this issue now.

@pjenvey - Ah. Okay, I'll put that in a PR.
