### ISSUE TITLE
Create a new release with only the pypy upgrade

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/tokenserver#192]
We ran into some notable [perf issues](https://bugzilla.mozilla.org/show_bug.cgi?id=1644955#c6) with the latest 1.5.6 release. Let's cut a new release with only [this change](https://github.com/mozilla-services/tokenserver/pull/168) so we can test that in isolation to try and narrow down the source of the problem.

**Comment by jrgm** [comment]
Just FYI, I branched off commit f19ac0e and got a docker image for that deployed on stage. Running the loadtest in a side by side comparison with 1.5.5 showed about the same performance (within the margin of error on the numbers).

**Comment by jrgm** [comment]
Sorry, branch off the commit and 1) fixed a flake8 error, 2) only installed cffi on cpython, and 3) allowed pypy in docker-entrypoint.sh

**Comment by jrconlin** [comment]
I'll admit that I'm a bit confused by what exactly is being asked for. 

Tokenserver OAuth verification is currently [done via the `fxa.oauth` library](https://github.com/mozilla-services/tokenserver/blame/master/tokenserver/verifiers.py#L227), which appears to do all the remote call outs and whatever token caching. This has been in tokenserver for a while. 

The [pypy specific changes](https://github.com/mozilla-services/tokenserver/pull/168) are newer, and are spread out across several PRs. ([168](https://github.com/mozilla-services/tokenserver/pull/168) & [191](https://github.com/mozilla-services/tokenserver/pull/191)). 

I'm not exactly sure what JWT processing you're talking about as it relates to bug [1644955][https://bugzilla.mozilla.org/show_bug.cgi?id=1644955#c6). It looks like #[193](https://github.com/mozilla-services/tokenserver/issues/193) might involve changes to the underlying `fxa` module. The only changes that relate to JWT processing I can find in the code are around [checking generation numbers](https://github.com/mozilla-services/tokenserver/commit/c8704565450409f609a1815440d2a5ed8f19843b) [see also](https://github.com/mozilla-services/tokenserver/commit/ee6c065dae50f86037abbbac51f0529a00beaff2). There might be some older changes that could impact performance, but I wonder if it might just be worth running

**Comment by rfk** [comment]
My pitch:

* Revert *just* the PyFxA version bump from https://github.com/mozilla-services/tokenserver/commit/51ddd8976902f0c88bd6f532fe4802f902287c5d, which is what brought in all the recent changes to handling OAuth tokens as JWTs.
* Get that deployed, knowing that any issues we encounter are likely from pypy or other infrastructural changes rather than from the OAuth JWTs work.
* Once we're happy with that, bring back the newer version of PyFxA and take a fresh look at the JWT-related issues such as #193.

**Comment by rfk** [comment]
> Running the loadtest in a side by side comparison with 1.5.5 showed about the same performance (within the margin of error on the numbers).

This sounds like good news, right? IIUC it means that the decrease in throughput you saw in previous tests is most likely due to the lack of caching (ref #193) than the switch to PyPy.

**Comment by jrgm** [comment]
> it means that the decrease in throughput you saw in previous tests is most likely due to the lack of caching (ref #193) than the switch to PyPy.

That's correct.
