### ISSUE TITLE
Figure out caching story for OAuth JWK request

### ISSUE THREAD

**Issue by rfk** [mozilla-services/tokenserver#193]
Ref https://github.com/mozilla-services/cloudops-deployment/pull/3914#issuecomment-649872052 for additional context.

In production, we run tokenserver alongside a squid proxy, with the intention that squid handles all outgoing traffic and caches the public keys that we fetch from FxA.

This works great for verifying BrowserID assertions: tokenserver talks to a local browserid-verifier instance, browserid-verifier talks to squid, squid requests the public keys from FxA and caches them, then returns them for browserid-verifier to use. All very nice.

I was expecting that we'd be able to do the same thing for the public keys used to verify JWT OAuth tokens: tokenserver calls PyFxA library, PyFxA talks to squid, squid fetches the public keys from FxA and caches them, then returns them for PyFxA to use. All very nice in theory.

I was wrong in practice.

In order for squid to provide any value, it must be able to see and cache the plaintext response from the FxA Server - that is, we have to deliberately let it see and interfere with the connection to https://oauth.accounts.firefox.com, trusting that the proxy will do all the TLS verification and authenticity checking and what-not. Most networking libraries *deliberately do not let you do this* because it's almost always going to be a security problem. It turns out that the BrowserID verifier has some [hand-crafted proxy handling code that does this](https://github.com/mozilla/browserid-local-verify/blob/bc1fa1428e3b6541dbad9e8f6c10a3e5ec2a28dd/lib/lookup.js#L21), which I was actually responsible for implementing many years ago, but I don't think I understood at the time how non-standard its behaviour was.

The python `requests` module does have support for proxying https request, but it does so in a way that maintains the end-to-end security of the request (by using the http `CONNECT` method to tunnel tcp traffic through the proxy) and which thus prevents squid from caching the responses.

I'm...not entirely sure what to do here. I can think of two options:

* Add similar code to what we have in the BrowserID verifier, doing the proxy connection in a way that defeats end-to-end security and trusts the proxy to do the right thing. I *think* we could do this as a [`TransportAdapter`](https://2.python-requests.org/en/master/user/advanced/#transport-adapters) in requests, but I don't know how fiddly it would be.
* Handle caching directly in the application, perhaps using [`requests-cache`](https://pypi.org/project/requests-cache/) package. This would probably be OK in practice, but makes the caching story a bit harder to understand/inspect from an ops perspective.

**Comment by fzzzy** [comment]
We're going to temporarily work around this by using an environment variable to pass the JWKS to the tokenserver.

**Comment by fzzzy** [comment]
https://github.com/mozilla-services/tokenserver/pull/197
