### ISSUE TITLE
Add Sentry Configuration

### ISSUE THREAD

**Issue by Micheletto** [mozilla-services/tokenserver#213]
Add a Sentry configuration for Tokenserver to help diagnose the problems associated with Bug [1672496](https://bugzilla.mozilla.org/show_bug.cgi?id=1672496).  See Sentry [documentation](https://docs.sentry.io/platforms/python/guides/pyramid/).

**Comment by Micheletto** [comment]
A SENTRY_DSN environment variable has been added to the Tokenserver configuration file through Bug [1678035](https://bugzilla.mozilla.org/show_bug.cgi?id=1678035).  The DSNs report to two new Tokenserver related projects in the Sync team on our Sentry instance.

**Comment by fzzzy** [comment]
This was fixed by an unrelated thing: https://github.com/mozilla-services/syncstorage-rs/commit/1a7e817a15d2ad0cb4a979e114cbcfa074402314
