### ISSUE TITLE
SciLinux: Unit Tests fail with ImportError: No module named cffi

### ISSUE THREAD

**Issue by jbonacci** [mozilla-services/tokenserver#30]
Sound familiar ;-)

https://github.com/mozilla-services/loads/issues/195
https://github.com/mozilla/fxa-auth-server/issues/268

So, this took a very simple install and build of TokenServer.
So, either I did not need pre-reqs, or they were already on my VM.

Here is a pastebin of the complete error list:
https://jbonacci.pastebin.mozilla.org/4032487

**Comment by rfk** [comment]
closing out old stale issues
