### ISSUE TITLE
Error in scripts/process_account_events.py

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/tokenserver#85]
Here is the log dump. The result is that the SQS queue didn't get cleared and it grew until monitoring kicked in. It looks like: 

1. data is not properly checked / sanitized
1. it crashes on [line 100](https://github.com/mozilla-services/tokenserver/blob/master/tokenserver/scripts/process_account_events.py#L100) 
1. exception bubbles up, process dies
1. systemd won't restart it anymore because it has died too many times and too quickly

```
Feb 26 19:25:15 docker[31898]: Processing account reset for u'<REDACTED>'
Feb 26 19:25:15 docker[31898]: Error while processing account deletion events
Feb 26 19:25:15 docker[31898]: Traceback (most recent call last):
Feb 26 19:25:15 docker[31898]: File "/app/tokenserver/scripts/process_account_events.py", line 100, in process_account_events
Feb 26 19:25:15 docker[31898]: backend.update_user(SERVICE, user, generation - 1)
Feb 26 19:25:15 docker[31898]: File "tokenserver/assignment/sqlnode/sql.py", line 321, in update_user
Feb 26 19:25:15 docker[31898]: 'email': user['email'],
Feb 26 19:25:15 docker[31898]: TypeError: 'NoneType' object has no attribute '__getitem__'
Feb 26 19:25:15 docker[31898]: Traceback (most recent call last):
Feb 26 19:25:15 docker[31898]: File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
Feb 26 19:25:15 docker[31898]: "__main__", fname, loader, pkg_name)
Feb 26 19:25:15 docker[31898]: File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
Feb 26 19:25:15 docker[31898]: exec code in run_globals
Feb 26 19:25:15 docker[31898]: File "/app/tokenserver/scripts/process_account_events.py", line 145, in <module>
Feb 26 19:25:15 docker[31898]: tokenserver.scripts.run_script(main)
Feb 26 19:25:15 docker[31898]: File "tokenserver/scripts/__init__.py", line 19, in run_script
Feb 26 19:25:15 docker[31898]: exitcode = main()
Feb 26 19:25:15 docker[31898]: File "/app/tokenserver/scripts/process_account_events.py", line 140, in main
Feb 26 19:25:15 docker[31898]: opts.aws_region, opts.queue_wait_time)
Feb 26 19:25:15 docker[31898]: File "/app/tokenserver/scripts/process_account_events.py", line 100, in process_account_events
Feb 26 19:25:15 docker[31898]: backend.update_user(SERVICE, user, generation - 1)
Feb 26 19:25:15 docker[31898]: File "tokenserver/assignment/sqlnode/sql.py", line 321, in update_user
Feb 26 19:25:15 docker[31898]: 'email': user['email'],
Feb 26 19:25:15 docker[31898]: TypeError: 'NoneType' object has no attribute '__getitem__'
Feb 26 19:25:16 systemd[1]: docker-tokenserver-account-events.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by mostlygeek** [comment]
@dannycoates  @rfk could you look into this. For now I rolled back yesterday's deployment and we should be ok until this is fixed.

**Comment by rfk** [comment]
Ugh, looks like we got a password-reset event for a user that's not currently active in sync, so we fail out trying to update their non-existent db record.  Should be fixed by https://github.com/mozilla-services/tokenserver/pull/86

**Comment by rfk** [comment]
@mostlygeek aside from fixing the specific but here, would it be useful to tweak the way this script works in the face of error?  Right now it just logs the exception and errors out, but we could e.g. keep trying to process other events in the queue.

**Comment by mostlygeek** [comment]
I think this would be nice and easy to add: 

1. log ignored, success and errors to datadog as a timeseries graph
2. log errors as events into datadog's event stream

That way we can alert on errors and see what they are without having to ssh into boxes.
