### ISSUE TITLE
Handle new fxa-tokenVerified attribute in the assertion

### ISSUE THREAD

**Issue by philbooth** [mozilla-services/tokenserver#89]
As per [FxA-83](https://github.com/mozilla/fxa/blob/phil/fxa-83/features/FxA-83-sign-in-confirmation-email/README.md#what-happens-when-an-unverified-client-requests-certificatesign), the auth server will soon include an `fxa-tokenVerified` attribute in the assertion. If the attribute is `false`, the assertion should be rejected.

**Comment by rfk** [comment]
For completeness, also nothing that if the property is *missing* then we should accept the assertion, for b/w compat reasons.

**Comment by philbooth** [comment]
Fixed in https://github.com/mozilla-services/tokenserver/pull/90.
