### ISSUE TITLE
Add a dockerflow endpoints

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/tokenserver#94]
When the docker container is built by circleci a version.json file is written into '/app/version.json'. When Tokenserver is run we should be able to curl `https://tokenserver_host/__version__` and it should return this JSON document. 

If the version.json file does not exist, a blank `{}` is an acceptable response. 

Also add a `__lbheartbeat__` endpoint that returns a 200 with a blank body.

**Comment by Natim** [comment]
Fixed with https://github.com/mozilla-services/tokenserver/commit/db8089ff1c593b793ef5719358116b980ea8d882
